version: '3.8'

services:
  ms-transacciones:
    build: .
    container_name: ms-transacciones
    ports:
      - "8080:8080"
    depends_on:
      db-postgres:
        condition: service_healthy  # Mejora la dependencia
    networks:
      - farmacia-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/db_transacciones?stringtype=unspecified
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-root}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=${JWT_SECRET:-TGVnYWN5UGhhcm1hY3lJc1RoZUJlc3RTRU5BUHJveWVjdDIwMjY=}
      - MS_PRODUCTOS_URL=${MS_PRODUCTOS_URL:-http://host.docker.internal:8081}

  db-postgres:
    image: postgres:15-alpine
    container_name: postgres-transacciones
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME:-db_transacciones}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-root}
      - TZ=America/Bogota
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - farmacia-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  farmacia-network:
    driver: bridge

volumes:
  postgres_data: