# ==============================================================
# CONFIGURACION DE BASE DE DATOS (Conectando a legacy03)
# ==============================================================
spring.application.name=inventory-service

# Cadena de conexion (Asegurate que el puerto sea 3306)
# Nota: En Docker usamos la variable de entorno, pero esto queda de respaldo
spring.datasource.url=jdbc:mysql://localhost:3307/legacy03?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=fabian
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================================================
# CONFIGURACION DE JPA / HIBERNATE
# ==============================================================
# 'update': Intenta actualizar la estructura si cambias algo en Java.
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola (Vital para depurar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true