# --- SERVIDOR ---
server.port=8083
server.servlet.context-path=/api/v1/ventas
spring.application.name=ms-transacciones

# --- CONEXIÓN OTRO MICROSERVICIO (INVENTARIO) ---
microservices.inventario.url=http://localhost:8081/api/v1/integracion-ventas

# --- BASE DE DATOS (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/db_transacciones
spring.datasource.username=postgres
spring.datasource.password=santi2703
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Update para no borrar tus datos previos de caja)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- SEGURIDAD ---
jwt.secret=TXlTZWNyZXRLZXlGb3JKV1RUb2tlbkxlZ2FjeVBoYXJtYWN5MjAyNVNwcmluZ0Jvb3Q0VmVyeVNlY3VyZUtleQecret=TXlTZWNyZXRLZXlGb3JKV1RUb2tlbkxlZ2FjeVBoYXJtYWN5MjAyNVNwcmluZ0Jvb3Q0VmVyeVNlY3VyZUtleQ