version: '3.8'

services:
  # --- CONTENEDOR DE LA APP (JAVA 21) ---
  ms-transacciones:
    build: .
    container_name: ms-transacciones
    restart: on-failure
    ports:
      - "8083:8083"
    environment:
      # Conexión a la BD del contenedor de abajo
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-transacciones:5432/db_transacciones
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=santi2703

      # Conexión al MS-INVENTARIO
      # 'host.docker.internal' apunta a tu localhost de Windows
      - MICROSERVICES_INVENTARIO_URL=http://host.docker.internal:8081/api/v1/inventario

      # Seguridad
      - JWT_SECRET=TXlTZWNyZXRLZXlGb3JKV1RUb2tlbkxlZ2FjeVBoYXJtYWN5MjAyNVNwcmluZ0Jvb3Q0VmVyeVNlY3VyZUtleQ
    depends_on:
      - db-transacciones
    networks:
      - farmacia-network
    extra_hosts:
      - "host.docker.internal:host-gateway" # Compatibilidad para Linux/Windows

  # --- CONTENEDOR DE BASE DE DATOS ---
  db-transacciones:
    image: postgres:15-alpine
    container_name: db-postgres-transacciones
    environment:
      - POSTGRES_DB=db_transacciones
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=santi2703
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - farmacia-network

volumes:
  postgres_data:

networks:
  farmacia-network:
    driver: bridge
