services:
  db-general:
    image: mysql:8.0
    container_name: farmacia_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fabian              # Contraseña configurada
      MYSQL_DATABASE: legacy_pharmacy_usuarios # Nombre de la base de datos
    ports:
      - "3307:3306"  # Exponemos el 3306 interno al 3307 externo para evitar conflictos
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - inventory-network

  ms-inventory:
    build: .
    container_name: ms-inventory
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-general:3306/legacy_pharmacy_usuarios?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=fabian
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db-general
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge
