USE legacy03;

- =============================================================================
-- SCRIPT DE MIGRACIÓN CON PRINCIPIOS ACTIVOS (CORAZÓN DEL MEDICAMENTO)
-- =============================================================================

-- 1. POBLAR CATEGORIAS
INSERT IGNORE INTO `categorias` (`nombre`, `activa`) VALUES ('GENERAL', 1);

-- 2. POBLAR LABORATORIOS
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('GENERICO', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('AG', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('GENFAR', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('BAYER', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('OTC', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('OPHARM', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('ANGLOPHARMA', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('NACIONAL DE QUIMICOS', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('DROGA BLANCA', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('ECAR', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('LABQUIFAR', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('LAPROFF', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('COASPHARMA', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('MEMPHIS', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('CUIDADO DEL BEBE', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('HARTUNG', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('JUHNIOS', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('AFR SAS', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('ABBOTT', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('ALIKIN', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('TOP GLOVE', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('OSA', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('SIEGFRIED', 1);
INSERT IGNORE INTO `laboratorios` (`nombre`, `activo`) VALUES ('NOVAMED', 1);

-- 3. POBLAR PRINCIPIOS ACTIVOS (Corazón del medicamento)
INSERT IGNORE INTO `principios_activos` (`nombre`) VALUES ('ACICLOVIR');
INSERT IGNORE INTO `principios_activos` (`nombre`) VALUES ('ACETATO DE ALUMINIO');
INSERT IGNORE INTO `principios_activos` (`nombre`) VALUES ('ACIDO ACETILSALICILICO');
INSERT IGNORE INTO `principios_activos` (`nombre`) VALUES ('ACIDO BORICO');
INSERT IGNORE INTO `principios_activos` (`nombre`) VALUES ('ACIDO FOLICO');
INSERT IGNORE INTO `principios_activos` (`nombre`) VALUES ('ACIDO FUSIDICO');
INSERT IGNORE INTO `principios_activos` (`nombre`) VALUES ('ACEITE MINERAL');
INSERT IGNORE INTO `principios_activos` (`nombre`) VALUES ('ACETILCISTEINA');
INSERT IGNORE INTO `principios_activos` (`nombre`) VALUES ('ACETAMINOFEN');

-- 4. INSERTAR PRODUCTOS
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('586', '0.770303807', 'Aciclovir 800Mg X Unidad En Tableta Laproff', (SELECT id FROM laboratorios WHERE nombre = 'GENERICO' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACICLOVIR' LIMIT 1), 946.0, 1.4, 0.0, 47.99, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1159', '0.770656902', 'Aciclovir Tableta 800Mg X Unidad', (SELECT id FROM laboratorios WHERE nombre = 'AG' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACICLOVIR' LIMIT 1), 540.0, 900.0, 0.0, 66.67, 0, 'Inactivo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1656', '0.77026051', 'Aciclovir Unguento Al 5 X 15 Mg', (SELECT id FROM laboratorios WHERE nombre = 'GENFAR' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACICLOVIR' LIMIT 1), 7.23, 10.5, 0.0, 45.17, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1756', '0.770212301', 'Acid Mante Baby X 30Gr', (SELECT id FROM laboratorios WHERE nombre = 'BAYER' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), NULL, 15.69, 16.3, 19.0, 3887.83, 0, 'Inactivo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('3007', '.ACD', 'Acid Mantle 400 Gr', (SELECT id FROM laboratorios WHERE nombre = 'OTC' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACETATO DE ALUMINIO' LIMIT 1), 23.5, 32.5, 0.0, 38.3, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1139', '0.7702123', 'Acid Mantle Locion X 120Ml', (SELECT id FROM laboratorios WHERE nombre = 'BAYER' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACETATO DE ALUMINIO' LIMIT 1), 16.4, 20.5, 0.0, 25.0, 0, 'Inactivo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1140', '0.770212301', 'Acid Mantle Locion X 400Ml', (SELECT id FROM laboratorios WHERE nombre = 'BAYER' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACETATO DE ALUMINIO' LIMIT 1), 32.08, 40.1, 0.0, 25.0, 0, 'Inactivo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1806', '0.770703551', 'Acido Acetilsalicico 100 Mg X 10 Ophalac', (SELECT id FROM laboratorios WHERE nombre = 'OPHARM' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO ACETILSALICILICO' LIMIT 1), 1.2, 2.0, 0.0, 66666.67, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('2990', '0.770354665', 'Acido Acetilsalicilico 100 Mg X 10 Tab', (SELECT id FROM laboratorios WHERE nombre = 'GENERICO' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO ACETILSALICILICO' LIMIT 1), 2.07, 3.5, 0.0, 69.23, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('56', '0.770703551', 'Acido Acetilsalicilico 100Mg Blister X 10 Tab', (SELECT id FROM laboratorios WHERE nombre = 'ANGLOPHARMA' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO ACETILSALICILICO' LIMIT 1), 1.1, 1.8, 0.0, 63636.36, 0, 'Inactivo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('55', '.', 'Acido Acetilsalicilico 100Mg Cj X 250 Tabletas', (SELECT id FROM laboratorios WHERE nombre = 'ANGLOPHARMA' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO ACETILSALICILICO' LIMIT 1), 28.5, 46.5, 0.0, 63.16, 0, 'Inactivo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1876', '0.7703714', 'Acido Borico X 250 Gra', (SELECT id FROM laboratorios WHERE nombre = 'NACIONAL DE QUIMICOS' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO BORICO' LIMIT 1), 2.2, 3.5, 0.0, 59.09, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1887', '0.106', 'Acido Borico X 10 Gr Nal. De Quimicos', (SELECT id FROM laboratorios WHERE nombre = 'DROGA BLANCA' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO BORICO' LIMIT 1), 212.0, 500.0, 0.0, 135.85, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('713', '.', 'Acido Borico X 10Gr', (SELECT id FROM laboratorios WHERE nombre = 'NACIONAL DE QUIMICOS' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO BORICO' LIMIT 1), 250.0, 500.0, 0.0, 100.0, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('2141', '0.7703714', 'Acido Borico X 125 Gr', (SELECT id FROM laboratorios WHERE nombre = 'DROGA BLANCA' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO BORICO' LIMIT 1), 1.9, 3.0, 0.0, 57.89, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('709', '.', 'Acido Borico X 250Gr', (SELECT id FROM laboratorios WHERE nombre = 'NACIONAL DE QUIMICOS' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO BORICO' LIMIT 1), 2.86, 4.9, 0.0, 71.43, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1875', '0.7703714', 'Acido Borico X 500 Gr', (SELECT id FROM laboratorios WHERE nombre = 'NACIONAL DE QUIMICOS' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO BORICO' LIMIT 1), 4.2, 6.72, 0.0, 60.0, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('706', '.', 'Acido Borico X 500Gr', (SELECT id FROM laboratorios WHERE nombre = 'NACIONAL DE QUIMICOS' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO BORICO' LIMIT 1), 4.5, 10.0, 0.0, 122.22, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1754', '0.770218401', 'Acido Folico 1 Mg', (SELECT id FROM laboratorios WHERE nombre = 'ECAR' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO FOLICO' LIMIT 1), 12.95, 1.0, 0.0, -92.28, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1797', '0.770701946', 'Acido Folico 1 Mg Caja X 10 Labquifar', (SELECT id FROM laboratorios WHERE nombre = 'LABQUIFAR' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO FOLICO' LIMIT 1), 5.1, 2.0, 0.0, -60.78, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('584', '0.770303805', 'Acido Folico 1Mg Blister X 10 Tabletas Laproff', (SELECT id FROM laboratorios WHERE nombre = 'GENERICO' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO FOLICO' LIMIT 1), 651.0, 1.2, 0.0, 84.33, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('583', '.', 'Acido Folico 1Mg Caja X 400 Tabletas', (SELECT id FROM laboratorios WHERE nombre = 'LAPROFF' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO FOLICO' LIMIT 1), 31.0, 50.0, 0.0, 61.29, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('2283', '0.770371203', 'Acido Fusidico 2 X 15 Gr Cohaspharma', (SELECT id FROM laboratorios WHERE nombre = 'COASPHARMA' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO FUSIDICO' LIMIT 1), 9.5, 9.5, 0.0, 0.0, 0, 'Inactivo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('168', '.', 'Acido Fusidico 2% Crema Topica X 15Gr', (SELECT id FROM laboratorios WHERE nombre = 'COASPHARMA' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO FUSIDICO' LIMIT 1), 6.2, 10.45, 0.0, 68.55, 0, 'Inactivo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('662', '0.77044121', 'Acido Fusidico 2% Crema Topica X 15Gr', (SELECT id FROM laboratorios WHERE nombre = 'MEMPHIS' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACIDO FUSIDICO' LIMIT 1), 5.7, 9.5, 0.0, 66.67, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('534', '.572625-A', 'Aceite Jhonsons Baby X 50Ml Jhonson Y Jhonson', (SELECT id FROM laboratorios WHERE nombre = 'CUIDADO DEL BEBE' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), NULL, 7.49, 9.8, 0.0, 30.84, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1112', '0.77022153', 'Aceite Julius Baby X 40Ml', (SELECT id FROM laboratorios WHERE nombre = 'HARTUNG' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), NULL, 2.8, 3.0, 0.0, 7142.86, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1639', '.', 'Aceite Julius X 90Ml', (SELECT id FROM laboratorios WHERE nombre = 'CUIDADO DEL BEBE' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), NULL, 3.45, 5.5, 0.0, 59.42, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('697', '0.7703714', 'Aceite Mineral X Onza', (SELECT id FROM laboratorios WHERE nombre = 'NACIONAL DE QUIMICOS' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACEITE MINERAL' LIMIT 1), 800.0, 2.0, 0.0, 0.15, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1488', '.', 'Aceite Para Bebe Viramina E 50 Ml', (SELECT id FROM laboratorios WHERE nombre = 'JUHNIOS' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), NULL, 1.44, 2.5, 19.0, 73.75, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('2259', '0.770999008', 'Aceite Para Bebe Julies X 80 Ml', (SELECT id FROM laboratorios WHERE nombre = 'AFR SAS' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), NULL, 5.5, 5.5, 0.0, 0.0, 0, 'Inactivo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('2539', '0.77091544', 'Aceite Para Bebe Julius 50 Ml', (SELECT id FROM laboratorios WHERE nombre = 'CUIDADO DEL BEBE' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), NULL, 1.65, 3.6, 0.0, 118.18, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1489', '.', 'Aceite Para Bebe Vitamina E 70 Ml', (SELECT id FROM laboratorios WHERE nombre = 'JUHNIOS' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), NULL, 1.81, 3.5, 19.0, 93.26, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('2083', '0.770371401', 'Aceite Recino 25 Cc', (SELECT id FROM laboratorios WHERE nombre = 'ABBOTT' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), NULL, 2.0, 2.0, 0.0, 0.0, 0, 'Inactivo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('2193', '0.770724298', 'Aceite Sensual Vainilla X 25 Ml', (SELECT id FROM laboratorios WHERE nombre = 'ALIKIN' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), NULL, 8.0, 12.0, 0.0, 50.0, 0, 'Inactivo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1360', '0.770724298', 'Aceite Sensual X 25Ml', (SELECT id FROM laboratorios WHERE nombre = 'TOP GLOVE' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), NULL, 6.0, 10.0, 0.0, 66.67, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1370', '0.77051373', 'Aceite Suave Osito 50 Ml', (SELECT id FROM laboratorios WHERE nombre = 'OSA' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), NULL, 2.7, 3.4, 19.0, 25925.93, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1407', '0.770735506', 'Acemuk 600 Acetilcisteina 600 Mg X 30 Comprimidos Efervescentes', (SELECT id FROM laboratorios WHERE nombre = 'SIEGFRIED' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACETILCISTEINA' LIMIT 1), 1.73, 2.5, 0.0, 44450.87, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('14', '0.770656902', 'Acetaminofe 500Mg Blister X 10 Tab. Ag', (SELECT id FROM laboratorios WHERE nombre = 'GENERICO' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), NULL, 598.0, 1.0, 0.0, 67.22, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('3064', '0.770595989', 'Acetaminofen Cafeina X 1 Unid.', (SELECT id FROM laboratorios WHERE nombre = 'GENERICO' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACETAMINOFEN' LIMIT 1), 686.0, 1.6, 0.0, 133.24, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('13', '.', 'Acetaminofen 500Mg Caja X 100 Tabletas', (SELECT id FROM laboratorios WHERE nombre = 'GENERICO' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACETAMINOFEN' LIMIT 1), 6.0, 10.0, 0.0, 66.67, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('580', '.', 'Acetaminofen 500Mg Caja X 300 Tabletas', (SELECT id FROM laboratorios WHERE nombre = 'LAPROFF' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACETAMINOFEN' LIMIT 1), 15.0, 30.0, 0.0, 100.0, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('920', '0.770303807', 'Acetaminofen Jarabe 90Ml', (SELECT id FROM laboratorios WHERE nombre = 'LAPROFF' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACETAMINOFEN' LIMIT 1), 2.47, 4.9, 0.0, 98.06, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('1801', '0.770303816', 'Acetaminofen / Codeina X 10 Tab.Laprof', (SELECT id FROM laboratorios WHERE nombre = 'GENERICO' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACETAMINOFEN' LIMIT 1), 4.32, 8.0, 0.0, 85.23, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('659', '.', 'Acetaminofen 150Mg/5Ml Jarabe X 120Ml', (SELECT id FROM laboratorios WHERE nombre = 'MEMPHIS' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACETAMINOFEN' LIMIT 1), 3.3, 5.8, 0.0, 75.76, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('166', '.', 'Acetaminofen 150Mg/5Ml Jarabe X 90Ml', (SELECT id FROM laboratorios WHERE nombre = 'COASPHARMA' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACETAMINOFEN' LIMIT 1), 2.1, 3.5, 0.0, 66.67, 0, 'Inactivo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('2604', '0.770354633', 'Acetaminofen 150Mg/5Ml Novamed', (SELECT id FROM laboratorios WHERE nombre = 'NOVAMED' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACETAMINOFEN' LIMIT 1), 3.43, 8.5, 0.0, 147.81, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('165', '0.770371204', 'Acetaminofen 500Mg Blister X 10 Unidades', (SELECT id FROM laboratorios WHERE nombre = 'GENERICO' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACETAMINOFEN' LIMIT 1), 598.0, 1.0, 0.0, 67.22, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('581', '0.770303805', 'Acetaminofen 500Mg Blister X 10 Unidades Laproff', (SELECT id FROM laboratorios WHERE nombre = 'GENERICO' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACETAMINOFEN' LIMIT 1), 416.0, 1.0, 0.0, 140.38, 0, 'Activo');
INSERT INTO `productos` (`codigo_interno`, `codigo_barras`, `nombre_comercial`, `laboratorio_id`, `categoria_id`, `principio_activo_id`, `precio_compra_referencia`, `precio_venta_base`, `iva_porcentaje`, `margen_minimo_porcentaje`, `stock_minimo`, `estado`) VALUES ('164', '.', 'Acetaminofen 500Mg Caja X 300 Tabletas Coaspharma', (SELECT id FROM laboratorios WHERE nombre = 'GENERICO' LIMIT 1), (SELECT id FROM categorias WHERE nombre = 'GENERAL' LIMIT 1), (SELECT id FROM principios_activos WHERE nombre = 'ACETAMINOFEN' LIMIT 1), 14.0, 28.0, 0.0, 100.0, 0, 'Activo');