server.port=${SERVER_PORT:8083}
server.servlet.context-path=/api/v1/ventas
spring.application.name=ms-transacciones


microservices.inventario.url=${URI_INVENTARIO:http://localhost:8081/api/v1/inventario}


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_transacciones}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:santi2703}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER-CLASS-NAME:org.postgresql.Driver}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5


jwt.secret=TXlTZWNyZXRLZXlGb3JKV1RUb2tlbkxlZ2FjeVBoYXJtYWN5MjAyNVNwcmluZ0Jvb3Q0VmVyeVNlY3VyZUtleQ